http:
  port: 8080

apiEndpoints:
  auth:
    paths:
      - /api/auth/*
  bkt:
    paths:
      - /api/bkt/*
  class:
    paths:
      - /api/class/*
  content:
    paths:
      - /api/content/*
  sync:
    paths:
      - /api/sync/*
  assignment:
    paths:
      - /api/assignment/*
  exam:
    paths:
      - /api/exam/*

serviceEndpoints:
  svcAuth:
    url: http://svc-auth:3001
  svcBkt:
    url: http://svc-bkt:3002
  svcClass:
    url: http://svc-class:3003
  svcContent:
    url: http://svc-content:3004
  svcSync:
    url: http://svc-sync:3005
  svcAssignment:
    url: http://svc-assignment:3006
  svcExam:
    url: http://svc-exam:3007

pipelines:
  default:
    apiEndpoints:
      - auth
      - bkt
      - class
      - content
      - sync
      - assignment
      - exam
    policies:
      - cors
      - rate-limit
      - jwt
      - proxy
