/**
 * Phosphor Icons Integration for VERVE AI Design System
 * 
 * This module provides a unified interface for using Phosphor icons throughout the application.
 * Icons are mapped by name for consistency and easy replacement.
 */

import {
  House,
  HouseSimple,
  Users,
  UsersThree,
  User,
  UserCircle,
  GraduationCap,
  Brain,
  ChartLine,
  ChartBar,
  Gear,
  GearSix,
  Shield,
  ShieldCheck,
  ShieldSlash,
  CheckCircle,
  CheckSquare,
  ListChecks,
  BookOpen,
  Book,
  Devices,
  Chalkboard,
  ChalkboardTeacher,
  DeviceMobile,
  SignOut,
  SignIn,
  Bell,
  BellSimple,
  MagnifyingGlass,
  Plus,
  Minus,
  X,
  Check,
  Pencil,
  Trash,
  Eye,
  EyeSlash,
  Download,
  Upload,
  File,
  FileText,
  Folder,
  FolderOpen,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  Clock,
  Star,
  Flag,
  Target,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  Info,
  Question,
  Warning,
  WarningCircle,
  WarningDiamond,
  SpinnerGap,
  Sun,
  Moon,
  Cloud,
  Lightning,
  Thermometer,
  Drop,
  ChartPie,
  ChartDonut,
  CurrencyDollar,
  Percent,
  Tag,
  Ticket,
  Trophy,
  Medal,
  Lock,
  LockOpen,
  Key,
  Copy,
  Clipboard,
  ClipboardText,
  Stack,
  GridFour,
  Layout,
  Sidebar,
  DotsThree,
  Phone,
  Envelope,
  EnvelopeSimple,
  Image,
  Images,
  Play,
  Pause,
  Stop,
  TrendUp,
  TrendDown,
  Pulse,
  FirstAid,
  ChartLineUp,
  ChartLineDown,
  MapTrifold,
  MapPin,
  MapPinSimple,
  MoonStars,
  CloudRain,
  Snowflake,
  LightningSlash,
  DropHalf,
  Wind,
  Tree,
  Plant,
  Flower,
  FlowerLotus,
  ChartBarHorizontal,
  ChartScatter,
  ChartPolar,
  CurrencyCircleDollar,
  ShoppingCart,
  CreditCard,
  Wallet,
  Receipt,
  Barcode,
  QrCode,
  LinkSimple,
  PaperPlaneTilt,
  VideoCamera,
  VideoCameraSlash,
  Microphone,
  Camera,
  SpeakerHigh,
  SpeakerLow,
  SpeakerSimpleSlash,
  Bluetooth,
  Usb,
  BatteryFull,
  Plug,
  Desktop,
  Laptop,
  DeviceTablet,
  HardDrives,
  HardDrive,
  Cpu,
  Memory,
  Database,
  CloudCheck,
  CloudArrowUp,
  CloudArrowDown,
  Folders,
  FolderSimple,
  FolderPlus,
  FilePlus,
  FilePdf,
  FileDoc,
  FileXls,
  FileZip,
  FileCode,
  TextT,
  TextAlignLeft,
  TextAlignCenter,
  TextAlignRight,
  ListBullets,
  ListNumbers,
  Note,
  NotePencil,
  Notebook,
  Newspaper,
  Article,
  ArticleMedium,
  SquaresFour,
  Rows,
  Columns,
  Alarm,
  Timer,
  Hourglass,
  HourglassSimple,
  Compass,
  NavigationArrow,
  TreeStructure,
  Broadcast,
  WifiHigh,
  WifiMedium,
  WifiLow,
  WifiSlash,
  UserGear,
  UserFocus,
  UserPlus,
  UserSquare,
  Coins,
  PiggyBank,
  ShoppingBag,
  Storefront,
  ListDashes,
  CurrencyGbp,
} from '@phosphor-icons/react';

/**
 * Icon mapping for VERVE AI Design System
 * Maps semantic icon names to Phosphor icon components
 */
export const iconMap = {
  // Navigation
  home: House,
  house: House,
  'house-simple': HouseSimple,
  users: Users,
  'users-three': UsersThree,
  user: User,
  'user-circle': UserCircle,
  graduation: GraduationCap,
  'graduation-cap': GraduationCap,
  'first-aid': FirstAid,
  brain: Brain,
  map: MapTrifold,
  'map-trifold': MapTrifold,
  'chart-line': ChartLine,
  'chart-line-up': ChartLineUp,
  'chart-line-down': ChartLineDown,
  'chart-bar': ChartBar,
  'chart-bar-horizontal': ChartBarHorizontal,
  settings: Gear,
  gear: Gear,
  'gear-six': GearSix,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-slash': ShieldSlash,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'list-checks': ListChecks,
  'list-dashes': ListDashes,
  'book-open': BookOpen,
  book: Book,
  devices: Devices,
  chalkboard: Chalkboard,
  'chalkboard-teacher': ChalkboardTeacher,
  'devices-mobile': DeviceMobile,
  'sign-out': SignOut,
  'sign-in': SignIn,
  bell: Bell,
  'bell-simple': BellSimple,
  search: MagnifyingGlass,
  'magnifying-glass': MagnifyingGlass,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  pencil: Pencil,
  trash: Trash,
  eye: Eye,
  'eye-slash': EyeSlash,
  download: Download,
  upload: Upload,
  file: File,
  'file-text': FileText,
  'file-plus': FilePlus,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  folders: Folders,
  'folder-simple': FolderSimple,
  calendar: Calendar,
  'calendar-blank': CalendarBlank,
  'calendar-check': CalendarCheck,
  clock: Clock,
  star: Star,
  flag: Flag,
  target: Target,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'caret-down': CaretDown,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  info: Info,
  question: Question,
  warning: Warning,
  'warning-circle': WarningCircle,
  'warning-diamond': WarningDiamond,
  spinner: SpinnerGap,
  'spinner-gap': SpinnerGap,
  sun: Sun,
  moon: Moon,
  'moon-stars': MoonStars,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-check': CloudCheck,
  'cloud-arrow-up': CloudArrowUp,
  'cloud-arrow-down': CloudArrowDown,
  lightning: Lightning,
  'lightning-slash': LightningSlash,
  thermometer: Thermometer,
  drop: Drop,
  'drop-half': DropHalf,
  wind: Wind,
  snowflake: Snowflake,
  'chart-pie': ChartPie,
  'chart-donut': ChartDonut,
  'chart-scatter': ChartScatter,
  'chart-polar': ChartPolar,
  currency: CurrencyDollar,
  'currency-circle-dollar': CurrencyCircleDollar,
  'currency-gbp': CurrencyGbp,
  percent: Percent,
  tag: Tag,
  ticket: Ticket,
  trophy: Trophy,
  medal: Medal,
  lock: Lock,
  'lock-open': LockOpen,
  key: Key,
  copy: Copy,
  clipboard: Clipboard,
  'clipboard-text': ClipboardText,
  stack: Stack,
  grid: GridFour,
  'squares-four': SquaresFour,
  layout: Layout,
  sidebar: Sidebar,
  dots: DotsThree,
  'dots-three': DotsThree,
  phone: Phone,
  envelope: Envelope,
  'envelope-simple': EnvelopeSimple,
  'paper-plane': PaperPlaneTilt,
  image: Image,
  images: Images,
  play: Play,
  pause: Pause,
  stop: Stop,
  trend: TrendUp,
  'trend-down': TrendDown,
  heartbeat: Pulse,
  compass: Compass,
  'map-pin': MapPin,
  'map-pin-simple': MapPinSimple,
  'navigation-arrow': NavigationArrow,
  'tree-structure': TreeStructure,
  tree: Tree,
  plant: Plant,
  flower: Flower,
  'flower-lotus': FlowerLotus,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  wallet: Wallet,
  receipt: Receipt,
  barcode: Barcode,
  'qr-code': QrCode,
  'video-camera': VideoCamera,
  'video-camera-slash': VideoCameraSlash,
  microphone: Microphone,
  camera: Camera,
  'speaker-high': SpeakerHigh,
  'speaker-low': SpeakerLow,
  'speaker-simple-slash': SpeakerSimpleSlash,
  bluetooth: Bluetooth,
  usb: Usb,
  'battery-full': BatteryFull,
  plug: Plug,
  desktop: Desktop,
  laptop: Laptop,
  'device-tablet': DeviceTablet,
  'device-mobile': DeviceMobile,
  'hard-drives': HardDrives,
  'hard-drive': HardDrive,
  cpu: Cpu,
  memory: Memory,
  database: Database,
  text: TextT,
  'text-align-left': TextAlignLeft,
  'text-align-center': TextAlignCenter,
  'text-align-right': TextAlignRight,
  'list-bullets': ListBullets,
  'list-numbers': ListNumbers,
  note: Note,
  'note-pencil': NotePencil,
  notebook: Notebook,
  newspaper: Newspaper,
  article: Article,
  'article-medium': ArticleMedium,
  rows: Rows,
  columns: Columns,
  alarm: Alarm,
  timer: Timer,
  hourglass: Hourglass,
  'hourglass-simple': HourglassSimple,
  broadcast: Broadcast,
  'wifi-high': WifiHigh,
  'wifi-medium': WifiMedium,
  'wifi-low': WifiLow,
  'wifi-slash': WifiSlash,
  'user-gear': UserGear,
  'user-focus': UserFocus,
  'user-plus': UserPlus,
  'user-square': UserSquare,
  coins: Coins,
  piggybank: PiggyBank,
  storefront: Storefront,
} as const;

/**
 * Icon component props type
 */
export type IconName = keyof typeof iconMap;
export type IconProps = React.ComponentPropsWithoutRef<'svg'> & {
  name: IconName;
  size?: number | string;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
};

/**
 * Dynamic Icon component that renders Phosphor icons by name
 */
export const Icon: React.FC<IconProps> = ({ name, size = 24, weight = 'regular', className, ...props }) => {
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in iconMap`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      weight={weight}
      className={className}
      {...props}
    />
  );
};

/**
 * Hook for using icons dynamically
 */
export const useIcon = () => {
  const IconWrapper: React.FC<{ name: IconName; props?: Omit<IconProps, 'name'> }> = ({ name, props }) => {
    const IconElement = iconMap[name];
    if (!IconElement) {
      console.warn(`Icon "${name}" not found in iconMap`);
      return null;
    }
    return <IconElement {...props} />;
  };
  IconWrapper.displayName = 'IconFromHook';
  
  const useIconResult = (name: IconName, props?: Omit<IconProps, 'name'>) => (
    <IconWrapper name={name} props={props} />
  );
  useIconResult.displayName = 'useIcon';
  
  return useIconResult;
};

export default Icon;
